apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    project: expense
spec:
  containers:
  #docker run -d --name naginx nginx
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    project: expense
spec:
  affinity:
    podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: project
                operator: In
                values:
                - expense
            topologyKey: "kubernetes.io/hostname"
  containers:
  #docker run -d --name naginx nginx
  - name: nginx
    image: nginx